version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=urlshorten'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: always

volumes:
  mysql-data:
